### ISSUE TITLE
Panic asserting `vlr_env[cand_vlrix].is_ref == is_ref`

### ISSUE THREAD

**Issue by ZekeMedley** [bytecodealliance/regalloc.rs#124]
I'm working on a Cranelift fronted that uses tagged pointers for types. Because I need garbage collection this requires using reference types and casting them back and forth to integers to tag them. For example:

```
    v3 = raw_bitcast.i64 v1
    v4 = bor_imm v3, 6
    v5 = raw_bitcast.r64 v4
```

I'm seeing panics in regalloc `assertion failed: vlr_env[cand_vlrix].is_ref == is_ref`. My best guess is that these casts are somehow related. This only happens sometimes, but have a reasonably small function that can cause the panic which I've attached below.

I was wondering if I could get some guidance on how to either change my code generation to avoid this issue or if this is a real issue in regalloc I'd be happy to take a stab at resolving it. Thanks for the help and great crate :) I'm happy to provide more details as needed.

```
function u0:0() -> r64 system_v {
    sig0 = (i64) -> r64 system_v
    sig1 = (r64, r64, r64) -> r64 system_v
    sig2 = (i64) -> r64 system_v
    sig3 = (i64) -> r64 system_v
    sig4 = (r64, r64, r64) -> r64 system_v
    sig5 = (r64, r64, r64) -> r64 system_v
    fn0 = colocated u0:2 sig0
    fn1 = colocated u0:5 sig1
    fn2 = colocated u0:2 sig2
    fn3 = colocated u0:2 sig3

block0:
    v0 = iconst.i64 8
    v1 = call fn0(v0)
    v2 = func_addr.r64 fn1
    store v2, v1
    v3 = raw_bitcast.i64 v1
    v4 = bor_imm v3, 6
    v5 = raw_bitcast.r64 v4
    v6 = raw_bitcast.i64 v5
    v7 = band_imm v6, -8
    v8 = raw_bitcast.r64 v7
    v9 = load.r64 v8
    v10 = iconst.i64 1
    v11 = raw_bitcast.r64 v10
    v12 = iconst.i64 8
    v13 = call fn2(v12)
    v14 = raw_bitcast.i64 v5
    v15 = band_imm v14, -8
    v16 = raw_bitcast.r64 v15
    v17 = load.r64 v16
    v18 = iconst.i64 1
    v19 = raw_bitcast.r64 v18
    v20 = iconst.i64 8
    v21 = call fn3(v20)
    v22 = iconst.i64 8
    v23 = raw_bitcast.r64 v22
    store v23, v21
    v24 = call_indirect sig4, v17(v16, v19, v21)
    store v24, v13
    v25 = call_indirect sig5, v9(v8, v11, v13)
    return v25
}
```

**Comment by bnjbvr** [comment]
Thanks for the report! Looks like this is an error when allocating and reusing spill slots in the backtracking allocator. The code comment around this assertion says that live ranges in the same equivalency class (= connected by a move) should all be reftypes ("reffy"), or none of them should be reffy. Here some of them are reffy, while some others aren't, which triggers the assertion. That's weird, because the same code comment states that the equivalency classes have been created in such a way that this shouldn't happen.

I don't know if @julian-seward1 would have time or interest looking into this, or even if it's worth doing so: most of the code in this crate is about to be deprecated and replaced by https://github.com/cfallin/regalloc2, which should start with implementing the same public API but will then evolve to unlock better performance. It would be interesting to test with regalloc2 as the default regalloc of cranelift, yet the setup is still a bit involved and requires a few custom patches (cc @cfallin).

**Comment by ZekeMedley** [comment]
Thanks for taking a look at this. I spent some time in a debugger stepping through this and from what I can tell the code that would normally mitigate this does indeed run so my best guess is that it is a bug somewhere.

I'm not familiar with how to run `.clif` files myself so the steps for reproducing on my end require running my compiler on an example program. If it's helpful I'm happy to provide steps for doing that. It's all the standard Rust toolchain / install so it's not that bad.

@cfallin - if it's ready I'd be happy to run this against regalloc2 and see if the issue happens there as well. I'd need a pointer to some instructions but don't mind taking a stab at it.

**Comment by bjorn3** [comment]
> I'm not familiar with how to run .clif files myself so the steps for reproducing on my end require running my compiler on an example program.

You can use `cargo run -p cranelift-tools -- compile` I think.

**Comment by cfallin** [comment]
@ZekeMedley thanks for this report and sorry you're hitting a bug here! I agree with @bnjbvr that it's probably not the best investment of time to try to fix this in the current allocator here (backtracking regalloc, or BTRA), unless the bug is quickly apparent to @julian-seward1.

To try this with regalloc2, one would: (i) check out the `regalloc2-2` branch of my wasmtime fork (cfallin/wasmtime), (ii) check out the `regalloc2` branch of my regalloc.rs fork (cfallin/regalloc.rs), (iii) check out the `initial-regalloc` branch of my regalloc2 fork (cfallin/regalloc2), all in sibling directories (the Cargo.tomls are set up for local paths for now for testing). Then build wasmtime and/or point your project toward cranelift-codegen in the local path. (In my fork regalloc2 is the default allocator.)

If that *does* work, then it confirms that this is likely a bug in BTRA; if it doesn't, then it's either a bug in regalloc2, or in Cranelift, or in the way your test cases are generated, though your use of raw_bitcast seems fine here.

One factor I will note is that the reference-types support in Cranelift basically treats pointers as opaque objects -- they flow in from the embedding, they flow back out, but they are never cast to other types -- so it's not totally surprising to me that this is exposing a bug of this form. Hopefully we can shake these issues out and make it more stable for this use-case :-)

**Comment by bjorn3** [comment]
```
v6 = raw_bitcast.i64 v5
v7 = band_imm v6, -8
v8 = raw_bitcast.r64 v7
v9 = load.r64 v8
v10 = iconst.i64 1
v11 = raw_bitcast.r64 v10
v12 = iconst.i64 8
v13 = call fn2(v12)
```

Cranelift is allowed to move the call to between casting `v5` to an int and casting `v7` to a reference (in this case the `load` inst would prevent this reordering though because the `call` could write to the same memory. this may or may not be the case for all code you emit). In this case no reference will end up in the stackmap potentially causing a use after free when the call causes a gc to happen.

**Comment by ZekeMedley** [comment]
> @bjorn3 You can use `cargo run -p cranelift-tools -- compile` I think.

Nice, thanks! I am able to reproduce using the latest commit to main by running `cargo run -p cranelift-tools -- compile --target x86_64 -D fn.clif` where `fn.clif` has the pasted function above.

> @bjorn3 Cranelift is allowed to move the call to between casting

This is good to know, thanks. I'll need to think about this more once I start writing / debugging the gc. Possible I'll have more questions then.

**Comment by ZekeMedley** [comment]
@cfallin thanks for the instructions on using regalloc2 :) I was hoping to get to this tonight but it looks like I'm running out of time here. I'll give this a stab and report back this weekend.

**Comment by julian-seward1** [comment]
From a purely armchair point of view (that is, based on what I remember about
the code from given that I last worked on it a year back), the following comes
to mind.  It may be that the ref-following analysis assumes that all live
ranges that are connected by a (coalescable) move instruction are either
ref-typed or non-ref typed.  That is, it assumes (and in effect) asserts that
there are no coalescable moves between a ref-typed and non-ref-typed live
range.  That would be, at a conceptual level, a type error in the incoming
program.  This appears also to sync with @bnjbvr's observations above.

What might be worth trying is to not tell the allocator that move instructions
resulting from lowering of raw_bitcast between r64 and i64 (in either
direction) are coalescable.  One way to do that would be to lower such nodes
to a new form of reg-to-reg move instruction in the back end, which is just
like the existing move insns, except that you don't tell the RA that they are
coalescable.  The effect would be that all such cases remain actual moves
(unless you get lucky and the RA just *happens* to give source and destination
the same real register).  So you could interpret this as a limitation of BTRA.

**Comment by ZekeMedley** [comment]
Finally got around to testing this with regalloc2 - looks like the issue persists.

**steps to reproduce**

1. Setup wasmtime with regalloc2 following @cfallin's instructions earlier in the thread.
2. Copy the contents of the example function above into a file `fn.clif`
3. From the wasmtime directory run `cargo run -p cranelift-tools -- compile --target x86_64 -D fn.clif`

This will error with `thread 'main' panicked at 'Minimal bundle with conflict!', /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/process.rs:763:13`.

<details>
<summary>Backtrace</summary>
<br>

```
thread 'main' panicked at 'Minimal bundle with conflict!', /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/process.rs:763:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/std/src/panicking.rs:541:12
   1: regalloc2::ion::process::<impl regalloc2::ion::data_structures::Env<F>>::process_bundle
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/process.rs:763:13
   2: regalloc2::ion::process::<impl regalloc2::ion::data_structures::Env<F>>::process_bundles
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/process.rs:41:13
   3: regalloc2::ion::<impl regalloc2::ion::data_structures::Env<F>>::run
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/mod.rs:106:9
   4: regalloc2::ion::run
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/ion/mod.rs:126:5
   5: regalloc2::run
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc2/src/lib.rs:1028:5
   6: regalloc::regalloc2::run
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc.rs/lib/src/regalloc2.rs:1047:18
   7: regalloc::allocate_registers_with_opts
             at /Users/zekemedley/Desktop/projects/lust/regalloc-bug/regalloc.rs/lib/src/lib.rs:626:39
   8: cranelift_codegen::machinst::compile::compile
             at ./cranelift/codegen/src/machinst/compile.rs:98:9
   9: cranelift_codegen::isa::x64::X64Backend::compile_vcode
             at ./cranelift/codegen/src/isa/x64/mod.rs:53:9
  10: <cranelift_codegen::isa::x64::X64Backend as cranelift_codegen::machinst::MachBackend>::compile_function
             at ./cranelift/codegen/src/isa/x64/mod.rs:64:21
  11: cranelift_codegen::context::Context::compile
             at ./cranelift/codegen/src/context.rs:197:26
  12: cranelift_codegen::context::Context::compile_and_emit
             at ./cranelift/codegen/src/context.rs:137:20
  13: clif_util::compile::handle_module
             at ./cranelift/src/compile.rs:81:29
  14: clif_util::compile::run
             at ./cranelift/src/compile.rs:52:9
  15: clif_util::main
             at ./cranelift/src/clif-util.rs:130:33
  16: core::ops::function::FnOnce::call_once
             at /rustc/c79419af0721c614d050f09b95f076da09d37b0d/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

@cfallin does anything here jump out to you? If you'd like I can open an issue over in your regalloc2 repository to look into this some more. Thanks for all the help so far :)

**Comment by cfallin** [comment]
@ZekeMedley thanks for trying this out! I suspect that this may be a bug either in how Cranelift lowers reftyped value uses in your case, or else in how it fails to find an issue in the CLIF during validation and then the mismatch (of some sort) propagates through. This is my suspicion because the assertion (minimal bundle with conflict) means that one vreg is constrained to two different conflicting locations (e.g., only stack, and only reg) in one "minimal bundle" (liverange fragment covering just one instruction). Such a regalloc input is unsolvable, so providing it to the regalloc is a bug upstream (i.e. in Cranelift).

So: would you be willing to file an issue on Cranelift with a CLIF input that reproduces this? That would be really helpful to look at later -- thanks!

(I'm on vacation currently until Jul 26 so may not respond right away but I can definitely look at this at some point.)

**Comment by ZekeMedley** [comment]
I'll close this for now as it seems like there is some investigation needed on the Cranelift side of things.
