### ISSUE TITLE
Add configuration/flags infrastructure

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/regalloc.rs#31]
There are several sorts of configuration options that the client might want to set:

* The allocation algorithm
* Parameters to the algorithm, to configure various heuristics
* Logging/tracing parameters
* Enabling self-consistency checks (e.g., the regalloc checker)

Right now, we just have the `RegAllocAlgorithm` enum that folds together item 1 and item 4 above (algorithm and checker-enabled flag). Ideally, we would have a "settings" or "flags" or "configuration" struct passed to the main entry point, and a way to construct this from environment variables, or command-line flags, or other client-provided configuration sources.

**Comment by bnjbvr** [comment]
I was thinking we could have a variant of `allocate_registers`, called `allocate_registers_with_options`, and that would take in a `AlgorithmWithOptions` enum instead of a `RegAllocAlgorithm`.

Then `AlgorithmWithOptions` would have one member attribute that's one of `LinearScanOptions` or `BacktrackingOptions`, so each can have its own settings. Then other common options can be other attributes of the parent data structure. All these new enums would implement the `Default` trait, so one can use the function ergonomically like this:

```
allocate_registers_with_options(func, AlgorithmWithOptions {
  algorithm: Backtracking {
    vreg_coalescing: false,
    ..Default::default()
  },
  request_block_annotations: true,
  ..Default::default()
}, rreg_universe)
```

It's a bit verbose, but that should cover all our uses cases. The other function that just takes in a `RegAllocAlgorithm` could stay, for users who don't care about specific features.
