### ISSUE TITLE
Assertions triggering during moves coalescing

### ISSUE THREAD

**Issue by bnjbvr** [bytecodealliance/regalloc.rs#52]
https://github.com/bytecodealliance/wasmtime/pull/1586 introduces explicit moves from SP (not allocatable) to other registers. However, this triggers an assertion failure in the backtracking allocator, during coalescing:

`assert!(iix_bounds.uses_len == 1);` (backtracking.rs:572)

I checked and the value was 0, instead of the expected 1. I don't think the change in the PR above `is_move` ought to be correct, so it'd be nice to see if there's something else to do to fix this.

It might be a bug in Cranelift itself, which might be feeding bad data to regalloc.

cc @julian-seward1

**Comment by julian-seward1** [comment]
Having looked at this .. I think the assertion is wrong.  It should be `<= 1` rather than `== 1`.  That would make it consistent with the assertion for `defs_len` on the next line.  The overall effect would be to ignore coalescing for moves in which either the source or dest regs have been "sanitised away".

The reason this happened is kind-of slackness on my part.  Until this bug, I had only ever seen
`mov sanitised_reg, normal_reg`
hence the assertions worked.  However, your example provides
`mov normal_reg, sanitised_reg` (where `sanitised_reg` = `SP`)

Which the proposed assertion change, I think we should be good to go.  However, I can't easily test it.  Can you?

**Comment by julian-seward1** [comment]
Fixed, 091ca7e5fedb823ba370b930d64677f6cc43afd7.  Thanks for the bug and for testing the fix.
